#ifndef TILE_BHV_H
#define TILE_BHV_H

#define TILE_BHV_NOTHING 0


#define TILE_BHV_PUSH_COLLIDE 1
#define TILE_BHV_PUSH_SLIME 2
#define TILE_BHV_PUSH_PUSHABLE 3


#define TILE_BHV_ENTER_DIE_WATER 1
#define TILE_BHV_ENTER_LIME 2


#define TILE_BHV_EXIT_LIME 1
#define TILE_BHV_EXIT_UNSTABLEGROUND 2

#endif
